# Site settings
baseurl = "https://www.wilber.co.ke/"

canonifyurls = true
languageCode = "en"
title = "Networks, Scripts, Musings"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-116430629-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#paginate = 3

uglyurls = true
#[permalinks]
# post = "/:year/:month/:day/:slug/"

[outputFormats.MyEnrichedFormat]
protocol = "https://"

[params]
	name = "Wilber Wanjira"
	job = "Computers"
	description = "Networks, Scripts, Musings,"
	bio = "[Networks](https://www.wilber.co.ke/categories/networks) | [Scripts](https://www.wilber.co.ke/categories/scripts) | [Writing](https://www.wilber.co.ke/categories/writing)"

	github = "wwanira"
	enableRSS = true
	
	title404 = "This is not the web page you are looking for."
	subtitle404 = ""

	disqusShortname = "wilberwanjira"
	enableDisqus = true

	enableGoogleAnalytics = true

	custom_css = []
	customJS  = []

	aboutAuthor = "Network Development Engineer"

	iconFont = "font-awesome"
  
  shareOnTwitter = true

  shareOnFacebook = true

[social]

  github-square = "https://github.com/wwanjira"
  linkedin = "https://www.linkedin.com/in/wilberwanjira/"
  twitter-square = "https://www.twitter.com/iam_wilber"
